### ISSUE TITLE
Remove the "inherit" option in select list

### ISSUE THREAD

**Issue by FredoVelcro** [pimcore/frontend-permission-toolkit#6]
Hello,

For our needs, we do not want the "inherit" option in the backend select field (Permission Resource object).
How can we override this ?
Thank you.
Best regards,
Fred

**Comment by fashxp** [comment]
only way right now is to overwrite the datatypes, e.g. https://github.com/pimcore/frontend-permission-toolkit/blob/master/src/CoreExtensions/ClassDefinition/PermissionResource.php#L21
